POST http://127.0.0.1:5000/api/expenses/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc3Njg1ODU2OSwianRpIjoiNDg0ZDRjNDktYWY4Ni00NjVkLWIzOGItYzgwNTFiMDQ2Njk2IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjEiLCJuYmYiOjE3NzY4NTg1NjksImNzcmYiOiI0ZDVjMDljZC1iZDg0LTRmZmItYTcyMS1jZjQ3ZmY3MDNiYjAiLCJleHAiOjE3NzY4NTk0Njl9.WHj5V5MLOmbaqZHCnt-hXb6dpoSdy8dK2X5PugfUoz4

{
  "amount": 250,
  "category": "Food",
  "description": "Lunch"
}
###
POST http://127.0.0.1:5000/api/expenses/
Content-Type: application/json

{
  "category": "Food"
}

###
GET http://127.0.0.1:5000/api/expenses/

###
GET http://127.0.0.1:5000/api/expenses/1

###
PATCH  http://127.0.0.1:5000/api/expenses/1
Content-Type: application/json

{
  "amount": 999,
  "category": "Gaming"
}

###
DELETE http://127.0.0.1:5000/api/expenses/1

###
GET http://127.0.0.1:5000/api/expenses/ai-insights
Content-Type: application/json

### Get all expenses
GET https://spendwise-ai-mn0e.onrender.com/api/expenses/

###
http://127.0.0.1:5000/api/budget?month=3&year=2026
Content-Type: application/json

###
POST http://127.0.0.1:5000/api/budget
Content-Type: application/json

{
  "amount": 10000,
  "month": 3,
  "year": 2026
}

###
GET http://127.0.0.1:5000/api/budget/history
Content-Type: application/json

### Register
POST http://127.0.0.1:5000/api/auth/register
Content-Type: application/json

{
    "name": "Test User",
    "email": "test@gmail.com",
    "password": "test123"
}

### Login
POST http://127.0.0.1:5000/api/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test123"
}