"""fix budget unique constraint

Revision ID: 83eb8c9928dc
Revises: 146f94463423
Create Date: 2026-04-22 21:18:39.216578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83eb8c9928dc'
down_revision = '146f94463423'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('unique_month_year'), type_='unique')
        batch_op.create_unique_constraint('unique_user_month_year', ['user_id', 'month', 'year'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_month_year', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('unique_month_year'), ['month', 'year'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
